# postgresql connection (supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DATABASE_CONNECTION_KEY}
#postgresql://postgres:Daisy,Mike1?@db.dfiwbxcueljdxfitsfbm.supabase.co:5432/postgres

# jpa/hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


token.signing.key=${TOKEN_SIGNING_KEY}
token.expiration=${TOKEN_EXPIRATION}

server.error.include-message=always